finanzen/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

finanzen/assets/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, jsonify)
from flask_login import current_user, login_required
import yfinance as yf
from finanzen import db
from finanzen.models import Asset
from finanzen.assets.forms import AssetForm

assets = Blueprint('assets', __name__)

@assets.route("/calc")
@login_required
def calc():
    assets = Asset.query.all()
    # Calculate total investment, return, and percentage return
    total_investment = sum([inv.total_price for inv in assets])
    # For simplicity, let's assume current price is fixed, in real cases, fetch from API
    current_price = 100  # Placeholder value, replace with actual logic
    total_return = sum([(current_price * inv.quantity) - inv.total_price for inv in assets])
    percentage_return = (total_return / total_investment) * 100 if total_investment > 0 else 0

    return render_template('calc_index.html', assets=assets, total_investment=total_investment, total_return=total_return, percentage_return=percentage_return)



@assets.route("/calc/new", methods=['GET', 'POST'])
@login_required
def new_calc():
    form = AssetForm()
    if form.validate_on_submit():
        asset = Asset(ticker=form.ticker.data, price=form.price.data, owner=current_user)
        db.session.add(asset)
        db.session.commit()
        flash('Your asset has been added!', 'success')
        return redirect(url_for('assets.calc'))
    return render_template('calc_new.html', title='New Asset', 
                           form=form, legend='New Asset') 


@assets.route('/search_ticker', methods=['GET'])
def search_ticker():
    query = request.args.get('query', '')
    if query:
        tickers = yf.Ticker(query).info
        return jsonify(tickers)
    return jsonify([])

# @posts.route("/post/<int:post_id>")
# def post(post_id):
#     post = Post.query.get_or_404(post_id)
#     return render_template('post.html', title=post.title, post=post)

# @posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
# @login_required
# def update_post(post_id):
#     post = Post.query.get_or_404(post_id)
#     if post.author != current_user:
#         abort(403)
#     form = PostForm()
#     if form.validate_on_submit():
#         post.title = form.title.data
#         post.content = form.content.data
#         db.session.commit()
#         flash('Your post has been updated!', 'success')
#         return redirect(url_for('posts.post', post_id=post.id))
#     elif request.method == 'GET':
#         form.title.data = post.title
#         form.content.data = post.content
#     return render_template('create_post.html', title='Update Post', 
#                            form=form, legend='Update Post') 

# @posts.route("/post/<int:post_id>/delete", methods=['POST'])
# @login_required
# def delete_post(post_id):
#     post = Post.query.get_or_404(post_id)
#     if post.author != current_user:
#         abort(403)
#     db.session.delete(post)
#     db.session.commit()
#     flash('Your post has been deleted!', 'success')
#     return redirect(url_for('main.home'))

@assets.route("/calcZen")
@login_required
def calcZen():
    return render_template('calcZen.html')

finanzen/main/routes.py
from flask import render_template, request, Blueprint, send_file
from finanzen.models import Post

main = Blueprint('main', __name__)

@main.route("/")
def index():
    return render_template('index.html')

@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=3)
    return render_template('home.html', posts=posts)

@main.route("/about")
def about():
    return render_template("about.html", title='About')

@main.route('/pdf')
def serve_pdf():
    # Path to the PDF file
    path_to_pdf = 'templates/Portfolio.pdf'
    return send_file(path_to_pdf)

finanzen/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from finanzen import db
from finanzen.models import Post
from finanzen.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', 
                           form=form, legend='New Post') 

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', 
                           form=form, legend='Update Post') 

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

finanzen/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from finanzen import db, bcrypt
from finanzen.models import User, Post
from finanzen.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from finanzen.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/account", methods=['GET', 'POST'])
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email 
    image_file = url_for('static', filename='profile_picts/' + current_user.image_file)
    return render_template('account.html', title='Account', 
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc()).\
            paginate(page=page, per_page=3)
    return render_template('user_posts.html', posts=posts, user=user)



@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instruction to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

finanzen/templates/2calc_index.html
{% extends "layout.html" %}
{% block content %}

<div class="container">
    <header>
        <h1>Investment Dashboard</h1>
        <nav>
            <a href="#">Add Investment</a>
        </nav>
    </header>

    <main>
        <table>
            <thead>
                <tr>
                    <th>Ticker</th>
                    <th>Quantity</th>
                    <th>Price (USD)</th>
                    <th>Total Price (USD)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>AAPL</td>
                    <td>10</td>
                    <td>150</td>
                    <td>1500</td>
                    <td>
                        <a href="#">Update</a> | 
                        <a href="#">Delete</a>
                    </td>
                </tr>
                <tr>
                    <td>GOOGL</td>
                    <td>5</td>
                    <td>2000</td>
                    <td>10000</td>
                    <td>
                        <a href="#">Update</a> | 
                        <a href="#">Delete</td>
                </tr>
                <tr>
                    <td>MSFT</td>
                    <td>8</td>
                    <td>250</td>
                    <td>2000</td>
                    <td>
                        <a href="#">Update</a> | 
                        <a href="#">Delete</a>
                    </td>
                </tr>
                <tr>
                    <td>TSLA</td>
                    <td>15</td>
                    <td>700</td>
                    <td>10500</td>
                    <td>
                        <a href="#">Update</a> | 
                        <a href="#">Delete</a>
                    </td>
                </tr>
                <tr>
                    <td>AMZN</td>
                    <td>2</td>
                    <td>3300</td>
                    <td>6600</td>
                    <td>
                        <a href="#">Update</a> | 
                        <a href="#">Delete</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </main>
    <nav>

        <a>Total Investment: $5000</a></br>
        <a>Total Return: $450</a></br>
        <a>Percentage Return: 9%</a></br>
    </nav>
</div>

<script src="scripts.js"></script>

{% endblock content %}

finanzen/templates/about.html
{% extends "layout.html" %}
{% block content %}

<!-- Bootstrap CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<style>
    body {
        background-color: #f4f7f6;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
    .contact-section {
        padding: 60px 0;
        background-color: #ffffff;
        box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
        max-width: 700px;
        margin: 40px auto;
    }
    .contact-section h1 {
        text-align: center;
        margin-bottom: 40px;
        font-size: 2.5rem;
        color: #333;
    }
    .form-group {
        margin-bottom: 25px;
    }
    .form-control {
        border-radius: 30px;
        padding: 20px;
    }
    .btn-custom {
        background-color: #007bff;
        color: #ffffff;
        border-radius: 30px;
        padding: 12px 30px;
        font-size: 1.2rem;
        transition: all 0.3s ease;
    }
    .btn-custom:hover {
        background-color: #0056b3;
        color: #ffffff;
    }
</style>
</head>
<body>

<div class="container">
<div class="contact-section">
    <h1>Contact Me</h1>
    <form>
        <div class="form-group">
            <label for="name">Your Name</label>
            <input type="text" class="form-control" id="name" placeholder="Enter your name">
        </div>
        <div class="form-group">
            <label for="email">Your Email</label>
            <input type="email" class="form-control" id="email" placeholder="Enter your email">
        </div>
        <div class="form-group">
            <label for="message">Your Message</label>
            <textarea class="form-control" id="message" rows="5" placeholder="Enter your message"></textarea>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-custom">Send Message</button>
        </div>
    </form>
</div>
</div>

<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

{% endblock content %}

finanzen/templates/bulayout.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">


        {% if title %}
            <title>Finanzen - {{ title }}</title>
        {% else %}
            <title>Finanzen</title>
        {% endif %}
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
              <div class="container">
                <a class="navbar-brand mr-4" href="/">Portfolio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                  <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                  </div>
                  <!-- Navbar Right Side -->
                  <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </nav>
        </header>

        <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
            <!-- <div class="content-section">
                <h3>Latest works</h3>
                <p class='text-muted'>Here you can find some of my recent works
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light"> <a href="{{ url_for('users.login') }}">finanZen-apps</a></li>
                    <li class="list-group-item list-group-item-light"> <a href="{{ url_for('posts.new_post') }}">finanZen-blog</a></li>
                    <li class="list-group-item list-group-item-light"> <a href="{{ url_for('assets.calc') }}">finanZen-calc</a></li>
                    <li class="list-group-item list-group-item-light">finanZen-econ</li>
                    <li class="list-group-item list-group-item-light"><a href="{{ url_for('main.about') }}">contact-me</a></li>
                </ul>
                </p>
            </div> -->
            </div>
        </div>
        </main>


            <!-- Optional JavaScript; choose one of the two! -->

            <!-- Option 1: Bootstrap Bundle with Popper -->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

            <!-- Option 2: Separate Popper and Bootstrap JS -->
            <!--
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
            -->

    </body>
</html>

finanzen/templates/calcZen.html
{% extends "layout.html" %}
{% block content %}
<h1>CalcZen</h1>
<label for="amount">Amount in USD:</label>
<input type="number" id="amount" placeholder="Enter amount" />

<label for="result">Converted to EUR:</label>
<input type="text" id="result" readonly />

<button onclick="convertCurrency()">Convert</button>

<script>
    // Sample exchange rate
    const exchangeRate = 0.85; // 1 USD = 0.85 EUR

    function convertCurrency() {
        const amount = document.getElementById("amount").value;
        const result = amount * exchangeRate;
        document.getElementById("result").value = result.toFixed(2);
    }
</script>

{% endblock content %}

finanzen/templates/calc_new.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
           <legend class="border-bottom mb-4">{{ legend }}</legend>

        <div class="container mt-5">
            <h1>Add Investment</h1>
            <form action="" method="POST">
                <div class="form-group">
                    <label for="ticker">Ticker</label>
                    <input type="text" class="form-control" id="ticker" name="ticker" required autocomplete="off">
                    <div id="ticker-list" class="list-group mt-2"></div>
                </div>
                <div class="form-group">
                    <label for="quantity">Quantity</label>
                    <select class="form-control" id="quantity" name="quantity" required>
                        {% for i in range(1, 11) %}
                            <option value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="price">Purchase Price (USD)</label>
                    <input type="number" step="0.01" class="form-control" id="price" name="price" required>
                </div>
                <div class="form-group">
                    <label for="date_purchased">Date Purchased</label>
                    <input type="date" class="form-control" id="date_purchased" name="date_purchased" required>
                </div>
                <button type="submit" class="btn btn-primary">Add Investment</button>
            </form>
        </div>
        
        <script>
        $(document).ready(function() {
            $('#ticker').on('input', function() {
                let query = $(this).val();
                if (query.length >= 2) {
                    $.ajax({
                        url: '{{ url_for("assets.search_ticker") }}',
                        type: 'GET',
                        data: { query: query },
                        success: function(data) {
                            $('#ticker-list').empty();
                            $.each(data, function(index, item) {
                                $('#ticker-list').append('<a href="#" class="list-group-item list-group-item-action ticker-item">' + item.symbol + ' - ' + item.shortName + '</a>');
                            });
                            $('.ticker-item').on('click', function() {
                                $('#ticker').val($(this).text().split(' - ')[0]);
                                $('#ticker-list').empty();
                            });
                        }
                    });
                } else {
                    $('#ticker-list').empty();
                }
            });
        });
        </script>
        

    </form>
</div>
{% endblock content %}

finanzen/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{  url_for('static', filename='profile_picts/' + post.author.image_file) }}">
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          </div>
          <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
      </article>
    {% endfor %}
    {% for page_num in posts.iter_pages() %}
      {% if page_num  %}
        {% if posts.page == page_num  %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
          ...
      {% endif %}
    {% endfor %}

{% endblock content %}

finanzen/templates/index.html
{% extends "layout.html" %}
{% block content %}

<div class="container">

    <div class="container mt-5">
        <h1>Welcome to FinanZen!</h1>
        <p>
            FinanZen is a platform designed to help you manage your finances with peace and clarity — a financial solution that brings Zen into your life. Whether you're tracking expenses, managing investments, or calculating currencies, FinanZen makes it easy and stress-free.
        </p>
        <p>You can explore the platform through the navigation bar below. From here, you'll discover features like ExpenZen for expense tracking, CalcZen for currency conversion, and a portfolio manager that helps you keep track of your assets.</p>


        <h3>Exciting News!</h3> 
        <p>I'm currently working on a mobile version of FinanZen for Apple devices. Soon, you'll be able to manage your finances on the go with the same Zen experience!</p>
        <div>
            <img src="https://imagizer.imageshack.com/img924/9269/LsiALi.png" alt="Resizable Image" class="resizable-img">
        </div>

        <h1>My Other Portfolio</h1>
        <p>
            For more details about me and my projects, feel free to check out my portfolio.
        </p>

        <div class="container my-5">
            <ul class="list-group">
                <li class="list-group-item list-group-item-light">
                    <a href="{{ url_for('users.login') }}" class="text-decoration-none text-dark">Backend Development : User Function with Flask</a>
                </li>
                <li class="list-group-item list-group-item-light">
                    <a href="{{ url_for('posts.new_post') }}" class="text-decoration-none text-dark">Backend Development : Posts Function with Flask</a>
                </li>
                <li class="list-group-item list-group-item-light">
                    <a href="{{ url_for('assets.calc') }}" class="text-decoration-none text-dark">Backend Development : Asset Calculation with Flask</a>
                </li>
                <li class="list-group-item list-group-item-light">
                    <a href="{{ url_for('users.login') }}" class="text-decoration-none text-dark">Backend Development : Economic List with Flask</a>
                </li>
                <li class="list-group-item list-group-item-light">
                    <a href="https://github.com/rubutar" class="text-decoration-none text-dark">Others on Github</a>
                </li>
            </ul>
            <iframe src="{{ url_for('main.serve_pdf') }}" width="100%" height="600px"></iframe>
          </div>

    </div>
 

{% endblock content %}

finanzen/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img"
            src="{{  url_for('static', filename='profile_picts/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>

<!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <!-- <div class="modal-body">
            You really want to delete this post?
            </div> -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

finanzen/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}